version: '3'

name: defactops-fourkeys

services:

  postgres-service:
    image: "postgres:16.2"
    container_name: postgres-service
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  defactops-ui:
    image: "defactops/defactops-ui:1.0.14"
    container_name: defactops-ui
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=postgres-service
      - POSTGRES_PORT=${POSTGRES_PORT}
      - GF_DATABASE_HOST=postgres-service:5432
      - GF_DATABASE_USER=${POSTGRES_USER}
      - GF_DATABASE_PASSWORD=${POSTGRES_PASSWORD}      
    ports:
      - 3000:3000
    links:
      - postgres-service

  defactops-app:
    image: "defactops/defactops-backend:1.0.21"
    container_name: defactops-backend
    environment:
      - GITLAB_API_TOKEN=${GITLAB_API_TOKEN}
      - GITLAB_PROJECT_ID=${GITLAB_PROJECT_ID}
      - GITLAB_ENVIRONMENT_NAME=${GITLAB_ENVIRONMENT_NAME}
      - JIRA_TOKEN=${JIRA_TOKEN}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=postgres-service
      - POSTGRES_PORT=${POSTGRES_PORT}      
      - LICENSE_TOKEN=${LICENSE_TOKEN}
    links:
      - postgres-service
