config:
  data:
    gitlab_project_id: "your-gitlab-project-number"
    gitlab_environment_name: "Production"
    jira_failure_label: "Regression"   

secrets:
  data:
    # DefactOps
    licence_token: "your-free-or-paid-license-key-from-defactops-website"

    # Gitlab
    gitlab_api_token: "your-gitlab-access-token"

    # Jira
    jira_token: "your-jira-access-token"

ingress:
  metadata:
    name:  http-ingress 
    annotations: {}
  spec:
    ingressClassName: nginx
    hostname: ""
    hostpath: /
  tls: 
    hostname: ""
    secretName: ""

postgresql:
  global:
    postgresql:
      auth:
        postgresPassword: "change-me-now!"
        username: "postuser"
        password: "change-me-now-too!"
        database: "defactops-db"

      service:
        ports:
          postgresql: "5432" 

  primary:
    initdbScripts:
      init.sql: |
        # This will be filled by the ConfigMap

    extraVolumes:
      - name: initdb-scripts
        configMap:
          name: defactops-config
          defaultMode: 420
          items:
          - key: init.sql
            path: init.sql

    extraVolumeMounts:
      - name: initdb-scripts
        mountPath: /docker-entrypoint-initdb.d